version: '3'
services:
  # Frontend
  react-app:
    image: amineis/miolafront:1.0
    ports:
      - "3000:3000"

  # Backend
  spring-app:
    image: amineis/miolaback:2.3
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my-network

  # MySQL 
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springboot
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
